language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules" # This will tell Travis CI to cache the dependencies
script: yarn install # Here you could also run the build step of your application
before_deploy: yarn add now --no-save # Install Now CLI on Travis
deploy:
  - provider: script
    script: now --public --token $NOW_TOKEN -e API_SECRET_CLOUDINARY=$API_SECRET_CLOUDINARY -e MONGO_PW=$MONGO_PW && now alias --token $NOW_TOKEN -e API_SECRET_CLOUDINARY=$API_SECRET_CLOUDINARY -e MONGO_PW=$MONGO_PW
    skip_cleanup: true